// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtbfvxjdgwdpsrgphkru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10YmZ2eGpkZ3dkcHNyZ3Boa3J1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5OTYwMTYsImV4cCI6MjA1NTU3MjAxNn0.vHlL0JjifNV6U--mxymJxVLT74MvYG3ZhEJG6WIkfJE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);